#!/bin/bash

# Quick setup script for GitHub Actions secrets and variables
# Run this script after setting up your repository

echo "GitHub Actions CI/CD Setup Guide"
echo "================================="
echo ""
echo "1. Go to your GitHub repository settings:"
echo "   https://github.com/YOUR_USERNAME/YOUR_REPO/settings/secrets/actions"
echo ""
echo "2. Add the following SECRETS:"
echo "   - PRIVATE_REGISTRY_USERNAME: your_registry_username"
echo "   - PRIVATE_REGISTRY_PASSWORD: your_registry_password_or_token"
echo "   - DOCKERHUB_USERNAME: your_dockerhub_username (optional)"
echo "   - DOCKERHUB_TOKEN: your_dockerhub_access_token (optional)"
echo ""
echo "3. Add the following VARIABLES:"
echo "   - PRIVATE_REGISTRY_URL: your-registry.company.com"
echo ""
echo "4. Create ENVIRONMENTS (optional):"
echo "   - staging"
echo "   - production"
echo ""
echo "5. Popular private registry URLs:"
echo "   - Docker Hub: docker.io"
echo "   - GitHub Container Registry: ghcr.io"
echo "   - AWS ECR: 123456789012.dkr.ecr.region.amazonaws.com"
echo "   - Azure ACR: yourregistry.azurecr.io"
echo "   - Google GCR: gcr.io/your-project-id"
echo "   - Harbor: harbor.company.com"
echo "   - Nexus: nexus.company.com"
echo ""
echo "6. Test your setup by pushing to main branch or running workflow manually"