version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: todolist-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: todolist123
      MONGO_INITDB_DATABASE: todolistDb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todolist-network

  # Node.js application service
  app:
    build: .
    container_name: todolist-app
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - todolist-network

volumes:
  mongodb_data:

networks:
  todolist-network:
    driver: bridge