---
- name: Configure EC2 instances for Todo App
  hosts: todo_servers
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install essential packages
      apt:
        name:
          - curl
          - git
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Docker Compose standalone
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Open port 4000 in security group (AWS handles firewall)
      debug:
        msg: "Ensure port 4000 is open in AWS Security Group"

    - name: Test Docker installation
      command: docker --version
      register: docker_version
      become_user: ubuntu

    - name: Display setup completion
      debug:
        msg: "✅ {{ inventory_hostname }} ready - {{ docker_version.stdout }}"