---
- name: Check Todo App Status
  hosts: todo_servers
  become_user: ubuntu
  gather_facts: no
  
  tasks:
    - name: Check running containers
      command: docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      register: containers_list

    - name: Check application health
      uri:
        url: "http://{{ ansible_host }}:4000"
        method: GET
        status_code: 200
        timeout: 5
      register: app_health
      delegate_to: localhost
      ignore_errors: yes

    - name: Display status
      debug:
        msg: |
          Server: {{ inventory_hostname }} ({{ ansible_host }})
          App: {{ 'Running ✅' if app_health.status == 200 else 'Not Running ❌' }}
          Containers: {{ containers_list.stdout_lines[1:] | join(', ') if containers_list.stdout_lines|length > 1 else 'None' }}