apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo-app
type: Opaque
data:
  # admin:todolist123 (base64 encoded)
  username: YWRtaW4=
  password: dG9kb2xpc3QxMjM=
  database: dG9kb2xpc3REYg==